apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Deployment template for a nodejs server.
    iconClass: icon-node
    tags: node
  name: ${NAME}-deployment-template
  namespace: devex-mpf-secure-tools
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes and load balances the application pods
    labels:
      app: ${NAME}
    name: ${API_DEPLOYMENT_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
    selector:
      deploymentconfig: ${API_DEPLOYMENT_NAME}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes the minio server
    labels:
      app: ${MINIO_DEPLOYMENT_NAME}
    name: ${MINIO_DEPLOYMENT_NAME}
  spec:
    ports:
    - name: 9000-tcp
      port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      deploymentconfig: ${MINIO_DEPLOYMENT_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${NAME}
    name: ${ROUTE_NAME}
  spec:
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: ${API_DEPLOYMENT_NAME}
      weight: 100
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: ${NAME}
    name: ${SSO_SECRET_NAME}
  stringData:
    secret: ${SSO_SECRET_VALUE}
  type: Opaque
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: ${NAME}
    name: ${API_SECRET_NAME}
  stringData:
    sessionSecret: ${API_SESSION_SECRET}
  type: Opaque
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: ${NAME}
    name: ${MINIO_SECRET_NAME}
  stringData:
    accessKey: ${MINIO_ACCESS_KEY}
    secretKey: ${MINIO_SECRET_KEY}
  type: Opaque
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${MINIO_VOLUME_NAME}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${MINIO_VOLUME_CAPACITY}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the minio server
    name: ${MINIO_DEPLOYMENT_NAME}
  spec:
    replicas: 1
    selector:
      app: minio
      deploymentconfig: ${MINIO_DEPLOYMENT_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: minio
          deploymentconfig: ${MINIO_DEPLOYMENT_NAME}
      spec:
        containers:
        - env:
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: accessKey
                name: ${MINIO_SECRET_NAME}
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: secretKey
                name: ${MINIO_SECRET_NAME}
          - name: MINIO_CONFIG_DIR
            value: /tmp
          - name: MINIO_DATA_DIR
            value: /data
          image: 172.50.0.2:5000/openshift/minio:latest
          imagePullPolicy: Always
          name: ${MINIO_DEPLOYMENT_NAME}
          ports:
          - containerPort: 9000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data
            name: minio-vol
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: minio-vol
          persistentVolumeClaim:
            claimName: ${MINIO_VOLUME_NAME}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - minio
        from:
          kind: ImageStreamTag
          name: minio:latest
          namespace: openshift
      type: ImageChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
    name: ${API_DEPLOYMENT_NAME}
  spec:
    replicas: 1
    selector:
      name: ${API_DEPLOYMENT_NAME}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: ${API_DEPLOYMENT_NAME}
        name: ${API_DEPLOYMENT_NAME}
      spec:
        containers:
        - env:
          - name: MINIO_ENDPOINT
            value: ${MINIO_DEPLOYMENT_NAME}.${NAMESPACE}.svc
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: accessKey
                name: ${MINIO_SECRET_NAME}
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: secretKey
                name: ${MINIO_SECRET_NAME}
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                key: sessionSecret
                name: ${API_SECRET_NAME}
          - name: SSO_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: secret
                name: ${SSO_SECRET_NAME}
          - name: PORT
            value: ${PORT}
          - name: NODE_ENV
            value: ${NODE_ENV}
          - name: APP_URL
            value: https://${API_DEPLOYMENT_NAME}-${NAMESPACE}.pathfinder.gov.bc.ca
          image: ' '
          livenessProbe:
            httpGet:
              path: /ehlo
              port: 8080
            initialDelaySeconds: 300
            timeoutSeconds: 3
          name: ${API_DEPLOYMENT_NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /ehlo
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 3
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${API_DEPLOYMENT_NAME}
        from:
          kind: ImageStreamTag
          name: ${NAME}:${IMAGE_TAG}
          namespace: ${IMAGE_NAMESPACE}
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The name assigned to all of the objects defined in this template.  You
    should keep this as default unless your know what your doing.
  displayName: Name
  name: NAME
  required: true
  value: secure-image-api
- description: The namespace of the OpenShift project containing the imagestream for
    the application.
  displayName: Image Namespace
  name: NAMESPACE
  required: true
- description: The name of the default route use to access this service.
  displayName: Application Route
  name: ROUTE_NAME
  required: true
  value: api
- description: The name given to the minio instance deployment.
  displayName: API deployment name
  name: API_DEPLOYMENT_NAME
  required: true
  value: api
- description: The namespace of the OpenShift project containing the imagestream for
    the application.
  displayName: Image Namespace
  name: IMAGE_NAMESPACE
  required: true
  value: devex-mpf-secure-tools
- description: The tag given to the built image.
  displayName: API Image Tag
  name: IMAGE_TAG
  required: true
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 512Mi
- description: The perferd port for the server to listen on.
  displayName: Server Port
  name: PORT
  required: true
  value: "8080"
- description: 'The node environment. Typically: develop, test, stage, or production'
  displayName: Node Environment
  name: NODE_ENV
  required: true
- description: The name given to the minio instance deployment.
  displayName: Minio deployment name
  name: MINIO_DEPLOYMENT_NAME
  required: true
  value: minio
- displayName: Name of the minio storage PV
  name: MINIO_VOLUME_NAME
  required: true
  value: minio-data
- displayName: Size of minio storage PV in Gi
  from: '[0-9]{3}Gi'
  name: MINIO_VOLUME_CAPACITY
  required: true
