apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "secure-image-api.fullname" . }}-cleanup-cron
  labels:
    app: {{ include "secure-image-api.name" . }}
    chart: {{ include "secure-image-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      activeDeadlineSeconds: 1800
      template:
        spec:
          activeDeadlineSeconds: 1800
          containers:
            - command:
                - /bin/sh
                - -c
                - find /data/ -mtime +7 -type f -delete {{ ternary " && find /session-data/ -mtime +2 -type f -delete" "" .Values.sessionPVC.enabled }}
              image: {{ .Values.global.imageRegistry }}/alpine:3.12
              imagePullPolicy: Always
              name: minio-clean
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /data
                  name: minio-data
                - mountPath: /session-data
                  name: session-data
          dnsPolicy: ClusterFirst
          imagePullSecrets:
            {{- range .Values.global.imagePullSecrets }}
            - name: {{ . }}
            {{- end }} 
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: minio-data
              persistentVolumeClaim:
                claimName: {{ .Release.Name }}-minio
            - name: session-data
              persistentVolumeClaim:
                claimName: {{ include "secure-image-api.fullname" . }}-session
  schedule: 0 1 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
