kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "secure-image-api.fullname" . }}-allow-traffic-from-gateway
spec:
  podSelector:
    matchLabels:
      {{- include "secure-image-api.selectorLabels" . | nindent 6 }}
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
      from:
        - namespaceSelector:
            matchLabels:
              environment: test
              name: 264e6f
    - ports:
        - protocol: TCP
          port: 8080
      from:
        - namespaceSelector:
            matchLabels:
              environment: prod
              name: 264e6f
