version: "3.6"
x-env: &defaults
  NODE_ENV:
  MINIO_ACCESS_KEY:
  MINIO_SECRET_KEY:
  MINIO_ENDPOINT: secimg-minio
  SSO_CLIENT_SECRET:
  SESSION_SECRET:
  APP_URL:
services:
  minio:
    container_name: secimg-minio
    image: minio/minio
    volumes:
      - type: bind
        source: ./minio_data
        target: /data
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 256m
    ports:
      - 9000:9000
    environment:
      <<: *defaults
    command: >
      server /data
  api:
    container_name: secimg-api
    image: node:10.16.3
    volumes:
      - type: bind
        source: ./
        target: /opt/app-root/src
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 256m
    working_dir: /opt/app-root/src
    ports:
      - 8080:8080
      - 9229:9229
    depends_on:
      - minio
    environment:
      <<: *defaults
      PORT: 8080
    command: >
      npm run dev