name: Android Test & Build
on:
  push:
    paths:
      - "android/app/**/*"
defaults:
  run:
    working-directory: ./android
jobs:
  testing:
    name: Lint Check and Testing
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Decrypt keystore properties
        run: |
          openssl version
          openssl aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -salt -d -a -in keystore.properties.enc -out keystore.properties -pass pass:${{ secrets.ANDROID_DECRYPT_KEY }}
      - name: Run Unit Tests
        run: |
          export ANDROID_NDK_HOME=
          ./gradlew test
