name: Android Make Release APK
on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./android
jobs:
  deploy:
    name: Make Android Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v1
      
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Decrypt keystore properties
        run: |
          openssl version
          openssl aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -salt -d -a -in keystore.properties.enc -out keystore.properties -pass pass:${{ secrets.ANDROID_DECRYPT_KEY }}
      
      - name: Run Gradle release task
        run: |
          export ANDROID_NDK_HOME=
          ./gradlew assembleRelease
      
      - name: Upload release artifact
        uses: actions/upload-artifact@v1
        with:
          name: SecureImage-release.apk
          path: app/build/intermediates/apk/release/app-release-unsigned.apk