name: Archive and Export ipa
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    name: Archiving and exporting ipa
    runs-on: macOS-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install gpg
        run: brew install gnupg
      - name: Setup profiles and certs
      - name: install xcpretty
        run: gem install xcpretty
      - name: Setup provisioning profile
        env:
          KEYS: ${{ secrets.KEYS }}
        run: ./.github/secrets/decrypt.sh
      - name: Archive project
        env:
          PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: ./.github/scripts/archive_adhoc.sh
      - name: Export .ipa
        run: ./.github/scripts/export_adhoc_ipa.sh
