name: Deploy iOS to App Center

on:
  push:
    paths:
      - "ios/SecureImage/**/*"

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
        
      - name: Switch XCode Version
        run: sudo xcode-select -s /Applications/Xcode_11.2.app

      - name: Cache Pods dependencies
        uses: actions/cache@v1
        with:
          path: ios/Pods
          key: ${{ runner.OS }}-pods-cache-${{ hashFiles('**/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-pods-cache-

      - name: Install pod dependencies
        run: |
          cd ios
          pod install
