name: Archive and Export ipa
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Archiving and exporting ipa
    runs-on: macOS-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install gpg
        run: brew install gnupg
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Setup provisioning profile
        env:
          KEYS: ${{ secrets.IOS_KEYS }}
        run: ./.github/secrets/decrypt_ios.sh
      - name: Archive project
        env:
          PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: ./.github/scripts/archive_ios.sh
      - name: Export .ipa
        run: ./.github/scripts/export_ios_ipa.sh
      - name: Upload .ipa
        uses: actions/upload-artifact@v1
        with:
          name: SecureImage.ipa
          path: $PWD/build/Apps/SecureImage.ipa
                