# This workflow is triggered when code is pushed to the master branch where there was a change in the ios folder 
# This workflow runs on macOS operating system and has a timeout of 200 minutes
name: Archive and Export ipa
on:
  push:
    branches:
      - master
    #paths:
      #- ios/**/*
      
jobs:
  deploy:
    name: Archiving and exporting ipa
    runs-on: macOS-latest # Update macOS version here if needed
      
    timeout-minutes: 200 # Workflow timeout in minutes
    
    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Switch XCode Version
        run: sudo xcode-select -s /Applications/Xcode_12.4.app
      # gpg is used to decrypt the profile and certificate
      - name: Install gpg
        run: brew install gnupg
      # xcpretty helps us see more useful logs when running the Xcode commands
      - name: Install xcpretty
        run: gem install xcpretty
      # Cocoapods is a dependency manager for iOS
      - name: Install Cocoapods
        run: sudo gem install cocoapods
      # decrypts profile and certificates and adds them to the keychain
      - name: Setup provisioning profile
        env:
          # passing the encryption password that is stored in Github Secrets
          IOS_KEYS: ${{ secrets.IOS_KEYS }}
        run: ./.github/secrets/decrypt_ios.sh
      - name: Verify installed secrets
        run: security find-identity -vp codesigning
      # instelling dependencies with cocoapods
      - name: Install dependencies
        run: cd $PWD/ios/ && pod install
      # Build project
      - name: Build app
        run: |
          cd ios
          xcodebuild \
          -workspace SecureImage.xcworkspace \
          -scheme SecureImage \
          clean build | xcpretty
      # Archiving iOS project
      # creates SecureImage.xcarchive file 
      - name: Archive project
        env:
          PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: ./.github/scripts/archive_ios.sh
      # exports the archived project and create the .ipa app file
      # here we use the specification in ios/exportOptions-adhoc.plist file to describe how the code is signed and should be exported.
      - name: Export .ipa
        run: ./.github/scripts/export_ios_ipa.sh
      # uploads the generated .ipa file using actions/upload-artifact@v1
      - name: Upload .ipa
        uses: actions/upload-artifact@v1
        with:
          name: SecureImage.ipa
          path: $PWD/build/Apps/SecureImage.ipa
                